with source_matches as (
    select * from {{ source('postgres_raw', 'fixtures') }}
)
select
    fixture_id,
    provider,
    source_provider,
    provider_league_id,
    competition_key,
    competition_type,
    date_utc,
    "timestamp" as fixture_timestamp,
    timezone,
    referee,
    referee_id,
    venue_id,
    venue_name,
    venue_city,
    cast(null as text) as venue_country,
    status_short,
    status_long,
    league_id,
    league_name,
    season,
    season_label,
    provider_season_id,
    nullif(trim(season_name), '') as season_name,
    season_start_date,
    season_end_date,
    round,
    stage_id,
    nullif(trim(stage_name), '') as stage_name,
    round_id,
    nullif(trim(round_name), '') as round_name,
    nullif(trim(group_name), '') as group_name,
    leg,
    attendance,
    weather_description,
    weather_temperature_c,
    weather_wind_kph,
    home_team_id,
    home_team_name,
    away_team_id,
    away_team_name,
    home_goals,
    away_goals,
    home_goals_ht,
    away_goals_ht,
    home_goals_ft,
    away_goals_ft,
    year,
    month,
    ingested_at,
    source_run_id,
    ingested_run
from source_matches
