with source_matches as (
    select * from {{ source('postgres_raw', 'fixtures') }}
)
select
    fixture_id,
    source_provider,
    date_utc,
    "timestamp" as fixture_timestamp,
    timezone,
    referee,
    referee_id,
    venue_id,
    venue_name,
    venue_city,
    cast(null as text) as venue_country,
    status_short,
    status_long,
    league_id,
    league_name,
    season,
    round,
    stage_id,
    round_id,
    attendance,
    weather_description,
    weather_temperature_c,
    weather_wind_kph,
    home_team_id,
    home_team_name,
    away_team_id,
    away_team_name,
    home_goals,
    away_goals,
    home_goals_ht,
    away_goals_ht,
    home_goals_ft,
    away_goals_ft,
    year,
    month,
    ingested_run
from source_matches
